### PR TITLE
use selectInput instead of inlineSelectInput

### PR DESCRIPTION
**Pull request by chad-klumb**
to support > 1 option in drop down menus

### CODE REVIEW

**Comment by martinamorris** [comment]
Thanks Chad.  This fixes the error.  

I'm seeing one more thing that looks like an error (even though it doesn't throw an error)

reprex:
select flomarriage
fit 3 models in sequence, and save each:
* edges
* + nodecov("wealth")
* + triangle
run the GOF for compare models

it looks like the second row of plots repeats model 1, because there is no nodecov("wealth") box in the model plot at the end of the column.

Screenshot (166)

**Comment by chad-klumb** [comment]
Not happening for me: in two pieces (since I can't zoom out any more),

top

bottom

Can you walk through those steps again and double check that the second model saved included the `nodecov("wealth")` term?

**Comment by martinamorris** [comment]
> Can you walk through those steps again and double check that the second model saved included the nodecov("wealth") term?

it was there.  but i had to shut down to teach.  let's leave that for now, b/c i've found another error

reprex
load faux.mesa.high
go to network descriptives tab
go to attributes subtab

i get the following error:

Screenshot (61)

**Comment by chad-klumb** [comment]
Also not happening for me, including with a brand new install of R 4.0.2 and all relevant packages:

attributes_subtab

**Comment by martinamorris** [comment]
interesting.  i'll try this.
@sgoodreau @smjenness head's up we may need to send out this suggestion.

**Pull request merged**
